version: "3.3"
services:
  gts-app-test:
    image: php:apache-stretch
    volumes:
      - ./php7:/var/www/html
    ports:
      - 8080:80
  gts-con:
    build: ./gts-con
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./gts-con/source/apps:/var/www/apps
      - ./gts-con/source/sites:/var/www/sites
    networks:
      frontend:
        aliases:
          - ${CON_HOST}
    env_file:
      - ./gts-con/.env
    depends_on:
      - mysql
  gts-app:
    build: ./gts-app
    ports:
      - 90:443
    volumes:
      - ./gts-app/source/apps:/var/www/apps
      - ./gts-app/source/sites:/var/www/sites
    networks:
      frontend:
        aliases:
          - ${APP_HOST}
      encryption:
    env_file:
      - ./gts-app/.env
    depends_on:
      - mysql
  gts-enc:
    build: ./gts-enc
    volumes:
      - ./gts-enc/source/sites:/var/www/sites
    networks:
      encryption:
        aliases:
          - ${ENC_HOST}
    env_file:
      - ./gts-enc/.env
    depends_on:
      - mysql
  mysql:
    image: mysql:5.6.40
    ports:
      - 3306:3306
    networks:
      - frontend
      - encryption
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
volumes:
    mysqldata:
networks:
  frontend:
  encryption: