<?php

$errors = array(
      3 => array(
        'en' => 'Invalid action',
        'he' => '',
        'ar' => '',
        'ru' => '',
    ),
      4 => array(
        'en' => 'cannot connect to REST API',
        'he' => 'לא ניתן להתחבר למערכת REST',
        'ar' => '',
        'ru' => '',
    ),
      5 => array(
        'en' => 'unexpected database error',
        'he' => 'שגיאת מסד נתונים',
        'ar' => 'خطأ في قاعدة البيانات',
        'ru' => 'ошибка базы данных',
    ),
      6 => array(
        'en' => 'access denied; invalid username and/or password',
        'he' => 'הגישה נדחתה; שם משתמש ו/או הסיסמה לא חוקיים',
        'ar' => 'تم رفض الطلب: اسم المستخدم و/أو كلمة المرور غير قانونيين',
        'ru' => 'допуск запрещен; неверное имя пользователя и/или пароль',
    ),
      7 => array(
        'en' => 'access denied; access-token expired',
        'he' => 'הגישה נדחתה; אסימון-הגישה פג',
        'ar' => 'تم رفض الطلب: أسيمون (قرص) الطلب انتهى',
        'ru' => 'допуск запрещен; маркер доступа просрочен',
    ),
      8 => array(
        'en' => 'Access denied. temporarily blocked for 15 minutes.',
        'he' => 'המנוי נחסם זמנית. אנא נסו שוב בעוד 15 דקות.',
        'ar' => 'تم رفض الطلب؛ مُغلق مؤقّتاً',
        'ru' => 'допуск запрещен; временная блокировка',
    ),
      9 => array(
        'en' => 'access denied; permanently blocked',
        'he' => 'הגישה נדחתה; נחסם לצמיתות',
        'ar' => 'تم رفض الطلب؛ مُغلق بشكل دائم',
        'ru' => 'допуск запрещен; постоянная блокировка',
    ),
    
     10 => array(
        'en' => 'invalid response from SHVA server',
        'he' => 'תגובה לא חוקית משרת שב"א',
        'ar' => 'رد فعل غير قانوني من الملقم شفا',
        'ru' => 'неверное срабатывание сервера ШВА',
    ),
     12 => array(
        'en' => 'access denied; password expired',
        'he' => 'הגישה נדחתה; הסיסמה פגה',
        'ar' => '',
        'ru' => 'допуск запрещен',
    ),
     13 => array(
        'en' => 'access denied; standing-orders disabled',
        'he' => 'הגישה נדחתה; מנגנון הוראות קבע כבוי',
        'ar' => 'تم رفض الطلب؛ جهاز الأوامر الدائمة مُطفَأ',
        'ru' => 'допуск запрещен; алгоритм постоянных поручений отключен',
    ),
     14 => array(
        'en' => 'invalid processor',
        'he' => 'מסלקה שגויה',
        'ar' => '',
        'ru' => '',
    ),
     15 => array(
        'en' => 'invalid SHVA identification tokens',
        'he' => 'נתוני גישה לשב"א שגויים',
        'ar' => 'بيانات الوصول لـ "شفا" خطأ',
        'ru' => 'неверные данные доступа к серверу ШВА',
    ),
     16 => array(
        'en' => 'invalid SHVA identification tokens or new password',
        'he' => 'נתונים גישה לשב"א או סיסמא חדשה שגויים',
        'ar' => 'بيانات الوصول لـ "شفا" أو كلمة المرور الجديدة خطأ',
        'ru' => 'данные доступа к серверу ШВА или новый пароль неверные',
    ),
     17 => array(
        'en' => 'invalid new password (minimum 6 characters, must have at least 1 digit and 1 character)',
        'he' => 'סיסמה חדשה שגויה (מינימום 6 תווים, חייבת לכלול לפחות גם תווים וגם מספרים)',
        'ar' => 'كلمة مرور جديدة خطأ (يجب أن تحتوي على الأقل على 6 علامات، حروف وأرقام )',
        'ru' => 'неверный новый пароль (обязан состоять из цифр и букв, минимум 6 знаков)',
    ),
     18 => array(
        'en' => 'cannot change password for test user',
        'he' => 'לא ניתן לשנות את הסיסמה עבור משתמש בדיקה',
        'ar' => 'لا يمكن تغيير كلمة المرور لمستخدم فحص',
        'ru' => 'невозможно изменить пароль для тестового пользователя',
    ),
     19 => array(
        'en' => 'cannot reuse a previously used password',
        'he' => 'לא ניתן לשנות סיסמא. הסיסמא הייתה בשימוש בעבר.',
        'ar' => '',
        'ru' => '',
    ),
    
     25 => array(
        'en' => 'invalid transaction-error-id',
        'he' => '',
        'ar' => '',
        'ru' => '',
    ),
    
     30 => array(
        'en' => 'invalid transaction-id',
        'he' => 'ערך transaction-id שגוי',
        'ar' => 'خطأ transactions   تنظيم',
        'ru' => 'ошибочное значение transaction-id',
    ),
     31 => array(
        'en' => 'invalid transaction type',
        'he' => '',
        'ar' => '',
        'ru' => '',
    ),
     32 => array(
        'en' => 'cannot add signature to a non-credit transaction',
        'he' => '',
        'ar' => '',
        'ru' => '',
    ),
     33 => array(
        'en' => 'cannot add signature to a non-credit transaction',
        'he' => '',
        'ar' => '',
        'ru' => '',
    ),
     34 => array(
        'en' => 'no data to update',
        'he' => '',
        'ar' => '',
        'ru' => '',
    ),
    
     35 => array(
        'en' => 'invalid standing-orders array',
        'he' => 'מערך standing-orders שגוי',
        'ar' => '',
        'ru' => '',
    ),
     36 => array(
        'en' => 'invalid standing-orders-ids array',
        'he' => 'מערך standing-orders-ids שגוי',
        'ar' => '',
        'ru' => '',
    ),
     37 => array(
        'en' => 'invalid standing-order-id',
        'he' => 'ערך standing-order-id שגוי',
        'ar' => '',
        'ru' => '',
    ),
     38 => array(
        'en' => 'duplicated transaction',
        'he' => 'עסקה כפולה',
        'ar' => '',
        'ru' => '',
    ),
    
     40 => array(
        'en' => 'invalid standing-orders-transactions array',
        'he' => 'מערך standing-orders-transactions שגוי',
        'ar' => '',
        'ru' => '',
    ),
     41 => array(
        'en' => 'invalid standing-order-transaction object',
        'he' => 'אובייקט standing-order-transaction שגוי',
        'ar' => '',
        'ru' => '',
    ),
    
     45 => array(
        'en' => 'invalid standing-orders-pending-transactions array',
        'he' => 'מערך standing-orders-pending-transactions שגוי',
        'ar' => '',
        'ru' => '',
    ),
     46 => array(
        'en' => 'invalid standing-order-pending-transaction object',
        'he' => 'אובייקט standing-order-pending-transaction שגוי',
        'ar' => '',
        'ru' => '',
    ),
    
     50 => array(
        'en' => 'a transaction for this standing-order has already been issued today',
        'he' => '',
        'ar' => '',
        'ru' => '',
    ),
    
     60 => array(
        'en' => 'invalid params array (limited to 10 params)',
        'he' => 'מערך params שגוי (מוגבל ל-10 params)',
        'ar' => '',
        'ru' => '',
    ),
     61 => array(
        'en' => 'invalid param object (name limited to 25 characters)',
        'he' => 'האובייקט param שגוי (ערך name מוגבל ל-25 תווים)',
        'ar' => '',
        'ru' => '',
    ),
     62 => array(
        'en' => 'invalid param object (value limited to 500 characters)',
        'he' => 'האובייקט param שגוי (ערך value מוגבל ל-500 תווים)',
        'ar' => '',
        'ru' => '',
    ),
    
     70 => array(
        'en' => 'insufficient information to process request',
        'he' => '',
        'ar' => '',
        'ru' => '',
    ),
     71 => array(
        'en' => 'failed sending sign up request',
        'he' => '',
        'ar' => '',
        'ru' => '',
    ),
    
     75 => array(
        'en' => 'Invalid e-mail address',
        'he' => 'כתובת הדוא"ל שהוזנה שגויה,נא לתקן ולשלוח בשנית',
        'ar' => '',
        'ru' => '',
    ),
     76 => array(
        'en' => 'Failed sending voucher',
        'he' => '',
        'ar' => '',
        'ru' => '',
    ),
	91 => array(
        'en' => 'Refund not supported for this terminal',
        'he' => 'מסוף זה אינו רשאי לבצע עסקאות זיכוי',
        'ar' => '',
        'ru' => '',
    ),    
    101 => array(
        'en' => 'Invalid amount',
        'he' => 'סכום שגוי',
        'ar' => '',
        'ru' => '',
    ),
    102 => array(
        'en' => 'invalid currency',
        'he' => 'מטבע שגוי',
        'ar' => '',
        'ru' => '',
    ),
    103 => array(
        'en' => 'invalid card number',
        'he' => 'מספר כרטיס האשראי שגוי',
        'ar' => '',
        'ru' => '',
    ),
    104 => array(
        'en' => 'invalid expiration date',
        'he' => 'תאריך התפוגה שגוי',
        'ar' => '',
        'ru' => '',
    ),
    105 => array(
        'en' => 'error calculating payments',
        'he' => 'שגיאה בחישוב תשלומים',
        'ar' => '',
        'ru' => '',
    ),
    106 => array(
        'en' => 'invalid payments-type value',
        'he' => 'סוג התשלומים שגוי',
        'ar' => '',
        'ru' => '',
    ),
    107 => array(
        'en' => 'invalid number of payments',
        'he' => 'מספר התשלומים שגוי',
        'ar' => '',
        'ru' => '',
    ),
    
    110 => array(
        'en' => 'invalid check number',
        'he' => 'מספר צ\'ק שגוי',
        'ar' => '',
        'ru' => '',
    ),
    111 => array(
        'en' => 'invalid bank number',
        'he' => 'מספר בנק שגוי',
        'ar' => '',
        'ru' => '',
    ),
    112 => array(
        'en' => 'invalid branch number',
        'he' => 'מספר סניף שגוי',
        'ar' => '',
        'ru' => '',
    ),
    113 => array(
        'en' => 'invalid account number',
        'he' => 'מספר חשבון שגוי',
        'ar' => '',
        'ru' => '',
    ),
    
    120 => array(
        'en' => 'invoices not supported',
        'he' => '',
        'ar' => '',
        'ru' => '',
    ),
    121 => array(
        'en' => 'invoice cannot be issued for a test credit transaction',
        'he' => '',
        'ar' => '',
        'ru' => '',
    ),
    122 => array(
        'en' => 'invalid invoice customer name',
        'he' => 'שם הלקוח בחשבונית שגוי',
        'ar' => '',
        'ru' => '',
    ),
    123 => array(
        'en' => 'invalid invoice description',
        'he' => 'פירוט החשבונית שגוי',
        'ar' => '',
        'ru' => '',
    ),
    
    130 => array(
        'en' => 'invalid name',
        'he' => 'שם לא חוקי',
        'ar' => '',
        'ru' => '',
    ),
    131 => array(
        'en' => 'invalid beginning date',
        'he' => 'תאריך התחלה שגוי',
        'ar' => '',
        'ru' => '',
    ),
    132 => array(
        'en' => 'invalid interval',
        'he' => 'תדירות הוראת הקבע שגויה',
        'ar' => '',
        'ru' => '',
    ),
    133 => array(
        'en' => 'invalid default amount',
        'he' => 'סכום ברירת המחדל שגוי',
        'ar' => '',
        'ru' => '',
    ),
    134 => array(
        'en' => 'invalid default currency',
        'he' => 'מטבע ברירת המחדל שגוי',
        'ar' => '',
        'ru' => '',
    ),
    
    137 => array(
        'en' => 'Next transaction due date cannot be in the past',
        'he' => 'תאריך החיוב הבא אינו יכול להיות בעבר',
        'ar' => '',
        'ru' => '',
    ),
    
    140 => array(
        'en' => 'invalid private key or passphrase',
        'he' => 'מפתח או סיסמת המפתח שגויים',
        'ar' => '',
        'ru' => '',
    ),
    145 => array(
        'en' => 'invalid statuses array',
        'he' => 'מערך statuses שגוי',
        'ar' => '',
        'ru' => '',
    ),
    
    150 => array(
        'en' => 'invalid merchant publickey',
        'he' => '',
        'ar' => '',
        'ru' => '',
    ),
    151 => array(
        'en' => 'credit card data encryption failed',
        'he' => '',
        'ar' => '',
        'ru' => '',
    ),
    
    199 => array(
        'en' => 'cannot connect to Credit Guard',
        'he' => '',
        'ar' => '',
        'ru' => '',
    ),
    200 => array(
        'en' => 'invalid Credit Guard response (%s: %s)',
        'he' => 'ארעה שגיאה %s: %s',
        'ar' => '',
        'ru' => '',
    ),
    201 => array(
        'en' => 'cannot connect to Semtec',
        'he' => '',
        'ar' => '',
        'ru' => '',
    ),
    202 => array(
        'en' => 'invalid Semtec response (%s: %s)',
        'he' => '',
        'ar' => '',
        'ru' => '',
    ),
    203 => array(
        'en' => 'invalid activation card (%s)',
        'he' => '',
        'ar' => '',
        'ru' => '',
    ),
    204 => array(
        'en' => 'cannot connect to AllCharge',
        'he' => '',
        'ar' => '',
        'ru' => '',
    ),
    205 => array(
        'en' => 'invalid AllCharge response (%s)',
        'he' => '',
        'ar' => '',
        'ru' => '',
    ),
    206 => array(
        'en' => 'credit payments support unavailable for AllCharge merchants',
        'he' => '',
        'ar' => '',
        'ru' => '',
    ),
    207 => array(
        'en' => 'refund-test support unavailable for AllCharge merchants',
        'he' => '',
        'ar' => '',
        'ru' => '',
    ),
    208 => array(
        'en' => 'refund request could not be matched to an existing transaction',
        'he' => 'לא ניתן לבצע עסקת ביטול או זיכוי מפני שחסרים נתונים',
        'ar' => '',
        'ru' => '',
    ),
    
    // SHVA errors (origanl codes + 500)
    501 => array(
        'en' => 'credit card marked blocked',
        'he' => 'כרטיס האשראי חסום',
        'ar' => '',
        'ru' => '',
    ),
    502 => array(
        'en' => 'credit card marked stolen',
        'he' => 'כרטיס האשראי גנוב',
        'ar' => '',
        'ru' => '',
    ),
    503 => array(
        'en' => 'call the credit card company',
        'he' => 'יש להתקשר לחברת האשראי',
        'ar' => '',
        'ru' => '',
    ),
    504 => array(
        'en' => 'transaction refused (probably credit exceeded)',
        'he' => 'סירוב (הכרטיס עבר את האשראי החודשי)',
        'ar' => '',
        'ru' => '',
    ),
    505 => array(
        'en' => 'credit card marked counterfeit',
        'he' => 'כרטיס מזויף',
        'ar' => '',
        'ru' => '',
    ),
    506 => array(
        'en' => 'invalid id or cvv2',
        'he' => 'CVV2 או תעודת זהות שגויים',
        'ar' => '',
        'ru' => '',
    ),
    507 => array(
        'en' => 'call the credit card company',
        'he' => 'יש להתקשר לחברת האשראי',
        'ar' => '',
        'ru' => '',
    ),
    530 => array(
        'en' => 'terminal does not have a parent-terminal defined in SHVA',
        'he' => 'למסוף אין הגדרת רב-מסוף בשב"א',
        'ar' => '',
        'ru' => '',
    ),
    532 => array(
        'en' => 'Terminal connectivity Error. Please contact support.',
        'he' => 'מסוף לא משדר קבוע. אנא פנה לתמיכה להמשך טיפול.',
        'ar' => '',
        'ru' => '',
    ),
    533 => array(
        'en' => 'invalid credit card',
        'he' => 'מספר כרטיס שגוי',
        'ar' => '',
        'ru' => '',
    ),
    534 => array(
        'en' => 'credit card or transaction type is unauthorized in this terminal',
        'he' => 'סוג הכרטיס או סוג העסקה אינם מורשים במסוף זה',
        'ar' => '',
        'ru' => '',
    ),
    535 => array(
        'en' => 'transaction credit type is not allowed for this card',
        'he' => 'סוג העסקה אינו מאושר עבור כרטיס זה',
        'ar' => '',
        'ru' => '',
    ),
    536 => array(
        'en' => 'credit card expired',
        'he' => 'הכרטיס פג תוקף',
        'ar' => '',
        'ru' => '',
    ),
    538 => array(
        'en' => 'unable to perform a transaction above ceiling for a debit card',
        'he' => 'לא ניתן לבצע עסקה מעל "תקרה" עבור כרטיס מסוג "דביט"',
        'ar' => '',
        'ru' => '',
    ),
    539 => array(
        'en' => 'wrong checksum digit',
        'he' => 'ספרת ביקורת לא תקינה',
        'ar' => '',
        'ru' => '',
    ),
    540 => array(
        'en' => 'terminal does not have a parent-terminal defined',
        'he' => 'למסוף לא מוגדר רב-מסוף',
        'ar' => '',
        'ru' => '',
    ),
    544 => array(
        'en' => 'terminal unauthorized to perform test transactions (J5)',
        'he' => 'המסוף אינו רשאי לבצע עסקאות בדיקה',
        'ar' => '',
        'ru' => '',
    ),
    557 => array(
        'en' => 'id-number missing',
        'he' => 'יש להזין תעודת זהות',
        'ar' => '',
        'ru' => '',
    ),
    558 => array(
        'en' => 'cvv2 missing',
        'he' => 'יש להזין CVV2',
        'ar' => '',
        'ru' => '',
    ),
    559 => array(
        'en' => 'cvv2 or id-number missing',
        'he' => 'CVV2 או תעודת זהות חסרים',
        'ar' => '',
        'ru' => '',
    ),
    561 => array(
        'en' => 'credit card not found or found twice',
        'he' => 'מספר הכרטיס לא קיים או קיים פעמים',
        'ar' => '',
        'ru' => '',
    ),
    569 => array(
        'en' => 'magnetic data string (track2) too short',
        'he' => 'נתוני הפס המגנטי קצרים מדי',
        'ar' => '',
        'ru' => '',
    ),
    573 => array(
        'en' => 'the credit card is carrying a chip and must be read using a smart-reader',
        'he' => 'כרטיס זה נושא שבב ולכן יש להשתמש בקורא מתאים',
        'ar' => '',
        'ru' => '',
    ),
    574 => array(
        'en' => 'rejected; credit card locked',
        'he' => 'נדחה; הכרטיס נעול',
        'ar' => '',
        'ru' => '',
    ),
    601 => array(
        'en' => 'terminal is unauthorized by the credit card company',
        'he' => 'המסוף אינו מאושר בחברת האשראי',
        'ar' => '',
        'ru' => '',
    ),
    607 => array(
        'en' => 'transaction amount is too high; please separate to smaller transactions',
        'he' => 'סכום העסקה גבוה מדי; יש לפצל למספר עסקאות עם סכום קטן יותר',
        'ar' => '',
        'ru' => '',
    ),
    611 => array(
        'en' => 'terminal is unauthorized for a payments transaction',
        'he' => 'המסוף אינו רשאי לבצע עסקאות תשלומים',
        'ar' => '',
        'ru' => '',
    ),
    612 => array(
        'en' => 'terminal is unauthorized for a payments transction without a signature',
        'he' => 'המסוף אינו רשאי לבצע עסקאות תשלומים ללא חתימה',
        'ar' => '',
        'ru' => '',
    ),
    613 => array(
        'en' => 'terminal is unauthorized for a transaction without a signature',
        'he' => 'המסוף אינו רשאי לבצע עסקאות ללא חתימה',
        'ar' => '',
        'ru' => '',
    ),
    615 => array(
        'en' => 'terminal is unauthorized for a transaction is dollars',
        'he' => 'המסוף אינו רשאי לבצע עסקאות בדולרים',
        'ar' => '',
        'ru' => '',
    ),
    624 => array(
        'en' => 'terminal is unauthorized for a payments by credit with an Isracard card',
        'he' => 'המסוף אינו רשאי לבצע עסקאות "קרדיט" עבור כרטיסי "ישראכרט"',
        'ar' => '',
        'ru' => '',
    ),
    625 => array(
        'en' => 'terminal is unauthorized for a payments by credit with an American Express card',
        'he' => 'המסוף אינו רשאי לבצע עסקאות תשלומים עבור כרטיסי "אמריקן אקספרס"',
        'ar' => '',
        'ru' => '',
    ),
    628 => array(
        'en' => 'terminal is unauthorized to accept Visa cards that start with "3"',
        'he' => 'המסוף אינו רשאי לבצע עסקאות עבור כרטיסי "ויזה" המתחילים בספרה "3"',
        'ar' => '',
        'ru' => '',
    ),
    629 => array(
        'en' => 'terminal is unauthorized for refund transactions above ceiling',
        'he' => 'המסוף אינו רשאי לבצע עסקאות זיכוי מעל ה"תקרה"',
        'ar' => '',
        'ru' => '',
    ),
    632 => array(
        'en' => 'credit card cannot be charged or refunded in dollars',
        'he' => 'הכרטיס אינו יכול לקבל זיכוי בדולרים',
        'ar' => '',
        'ru' => '',
    ),
    633 => array(
        'en' => 'this card has expired according to Isracard',
        'he' => 'הכרטיס פג תוקף ע"פ "ישראכרט"',
        'ar' => '',
        'ru' => '',
    ),
    634 => array(
        'en' => 'credit card number of digits is invalid according to Isracard',
        'he' => 'מספר כרטיס האשראי שגוי ע"פ "ישראכרט"',
        'ar' => '',
        'ru' => '',
    ),
    635 => array(
        'en' => 'credit card cannot be charged or refunded in dollars according to Isracard',
        'he' => 'לא ניתן לבצע עסקאות בדולרים עבור כרטיס זה ע"פ "ישראכרט"',
        'ar' => '',
        'ru' => '',
    ),
    636 => array(
        'en' => 'credit card cannot be charged or refunded in dollars according to VISA',
        'he' => 'לא ניתן לבצע עסקאות בדולרים עבור כרטיס זה ע"פ "ויזה"',
        'ar' => '',
        'ru' => '',
    ),
    637 => array(
        'en' => 'the first 7 digits of the credit card are invalid according to Diners',
        'he' => '7 הספרות הראשונות של כרטיס זה שגויות ע"פ "דיינרס"',
        'ar' => '',
        'ru' => '',
    ),
    638 => array(
        'en' => 'credit card cannot be used with payments transactions according to Isracard',
        'he' => 'כרטיס זה אינו רשאי לבצע עסקאות תשלומים ע"פ "ישראכרט"',
        'ar' => '',
        'ru' => '',
    ),
    639 => array(
        'en' => 'number of payments is too large according to Isracard',
        'he' => 'מספר התשלומים גדול מדי ע"פ "ישראכרט"',
        'ar' => '',
        'ru' => '',
    ),
    651 => array(
        'en' => 'terminal is unauthorized for international credit cards',
        'he' => 'מסוף זה אינו מורשה לבצע עסקאות עבור כרטיסים בינלאומיים',
        'ar' => '',
        'ru' => '',
    ),
    655 => array(
        'en' => 'the amount for this credit transaction is too low',
        'he' => 'סכום עסקה זו נמוך מדי',
        'ar' => '',
        'ru' => '',
    ),
    656 => array(
        'en' => 'the number of payments for this credit transaction is invalid',
        'he' => 'מספר התשלומים עבור עסקת "קרדיט" זו הינו נמוך מדי',
        'ar' => '',
        'ru' => '',
    ),
    657 => array(
        'en' => 'this credit card number and the chosen payment method are not supported by this terminal',
        'he' => 'תקרה 0 לסוג כרטיס זה בעיסקה עם אשראי רגיל או קרדיט',
        'ar' => '',
        'ru' => '',
    ),
    663 => array(
        'en' => 'American Express card originated abroad is unauthorized for a payment transaction',
        'he' => 'כרטיס "אמריקן אקספרס" זה הונפק בחו"ל ולכן לא ניתן לבצע עסקת תשלומים',
        'ar' => '',
        'ru' => '',
    ),
    668 => array(
        'en' => 'terminal is unauthorized for a transaction in dollars for this credit type',
        'he' => 'המסוף אינו רשאי לבצע עסקה בדולרים עבור סוג עסקה זו.',
        'ar' => '',
        'ru' => '',
    ),
    700 => array(
        'en' => 'SHVA internal error',
        'he' => 'שגיאה פנימית בשב"א',
        'ar' => '',
        'ru' => '',
    ),
    756 => array(
        'en' => 'transaction number is not unique per transaction date',
        'he' => 'מספר העסקה אינו חד-חד-ערכי עבור תאריך העסקה',
        'ar' => '',
        'ru' => '',
    ),
    757 => array(
        'en' => 'cannot find required information',
        'he' => 'לא ניתן למצוא את הנתונים הדרושים',
        'ar' => '',
        'ru' => '',
    ),
    760 => array(
        'en' => 'missing or incorrect arguments were passed to the function',
        'he' => 'נשלחו נתונים שגויים לפונקציה',
        'ar' => '',
        'ru' => '',
    ),
    780 => array(
        'en' => 'timeout',
        'he' => 'עבר זמן המקסימלי לביצוע העסקה',
        'ar' => '',
        'ru' => '',
    ),
    901 => array(
        'en' => 'Card reader issue. Please contact support.',
        'he' => 'קורא הכרטיסים לא תקין. אנא נסה שנית או הקלד ידנית.',
        'ar' => '',
        'ru' => '',
    ),
    814 => array(
        'en' => 'The transaction was already cancelled',
        'he' => 'העסקה כבר בוטלה בעבר',
        'ar' => '',
        'ru' => '',
    ),
    914 => array(
        'en' => 'Card reader issue. Please contact support.',
        'he' => 'קורא הכרטיסים לא תקין. אנא נסה שנית או הקלד ידנית.',
        'ar' => '',
        'ru' => '',
    ),
);

?>